#name: Build and Push with Buildah
#
#on:
#  push:
#    branches: [main]
#  workflow_dispatch:
#
#env:
#  IMAGE_NAME: docker-raidmetrics-prometheus-exporter
#  IMAGE_TAG: main
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repo
#        uses: actions/checkout@v4
#
#      - name: Install Buildah
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y buildah
#
#      - name: Install additional
#        run: |
#          sudo apt-get install -y tree
#
#
#      - name: debug tree
#        run: |
#          pwd && echo \n && tree
#
#      - name: Log in to DockerHub
#        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | buildah login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin docker.io
#
#      - name: Build image with Buildah
#        run: |
#          buildah bud \
#            --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
#            --file Dockerfile \
#            .
#
#      - name: Push image to DockerHub
#        run: |
#          buildah push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}